development:
  adapter: postgresql
  database: restaurantdev
  host: localhost

# Warning: The database defined as "test" will be erased and
# re-generated form your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: restauranttest
  host: localhost

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>