development:
  adapter: postgresql
  database: restaurantdev
  host: localhost
  username: carlos
  password: latino

# Warning: The database defined as "test" will be erased and
# re-generated form your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: restauranttest
  host: localhost
  username: carlos
  password: latino

production:
  adapter: postgresql
  database: restaurantprod
  host: localhost
  username: carlos
  password: latino